/*
 ============================================================================
 Name        : Lab6.c (memory.c)
 Author      : Austin Tian
 Revised by  :
 Version     :
 Copyright   : Copyright 2023
 Description : Lab 6 in C, ANSI-C Style
 ============================================================================
 */

#include "header.h"

// Menu for the testing.
char *menu =    "\n" \
                " ***********Please select the following options**********************\n" \
                " *    This is the memory operation menu (Lab 6)                     *\n" \
                " ********************************************************************\n" \
                " *    1. Write a double-word (32-bit) to the memory                 *\n"  \
                " ********************************************************************\n" \
                " *    2. Read a byte (8-bit) data from the memory                   *\n" \
                " *    3. Read a double-word (32-bit) data from the memory           *\n" \
                " ********************************************************************\n" \
                " *    4. Generate a memory dump from any memory location            *\n" \
                " ********************************************************************\n" \
                " *    e. To Exit, Type 'e'  or 'E'                                  *\n" \
                " ********************************************************************\n";

//---------------------------------------------------------------
// Generate a random number between 0x00 and 0xFF.
unsigned char rand_generator()
{
    return rand() % 255;
}

//---------------------------------------------------------------
void free_memory(char *base_address)
{
    free(base_address);  // free memory after use to avoid memory leakage.
    return;
}

//---------------------------------------------------------------
char *init_memory()
{
    char *mem = malloc(MEM_SIZE);  // allocate 1M bytes of memory

    // Step 1: Fill every byte of the 1M memory space with a random number.
    // Loop through each index and store a randomly generated byte value.
    int i;
    for (i = 0; i < MEM_SIZE; i++)
    {
        mem[i] = (char)rand_generator();
    }

    return mem;
}

//---------------------------------------------------------------
void write_dword(const char *base_address, const int offset, const unsigned int dword_data)
{
    // Step 2: Write a 32-bit double-word to address (base_address + offset).
    // Cast target address to unsigned int pointer so all 4 bytes are written at once.
    unsigned int *target = (unsigned int *)(base_address + offset);
    *target = dword_data;

    printf("Written 0x%08X to address: %p (offset: 0x%X)\n",
           dword_data, (void *)(base_address + offset), offset);
}

//---------------------------------------------------------------
unsigned char read_byte(const char *base_address, const int offset)
{
    // Step 3: Read a single byte from address (base_address + offset).
    // Use unsigned char pointer to prevent sign-extension of the value.
    unsigned char byte_data = *((unsigned char *)(base_address + offset));

    printf("Byte read from address %p (offset: 0x%X): 0x%02X\n",
           (void *)(base_address + offset), offset, byte_data);

    return byte_data;
}

//---------------------------------------------------------------
unsigned int read_dword(const char *base_address, const int offset)
{
    // Step 4: Read a 32-bit double-word from address (base_address + offset).
    // Cast to unsigned int pointer to read all 4 bytes at once.
    unsigned int dword_data = *((unsigned int *)(base_address + offset));

    printf("Double-word read from address %p (offset: 0x%X): 0x%08X\n",
           (void *)(base_address + offset), offset, dword_data);

    return dword_data;
}

//---------------------------------------------------------------
void memory_dump(const char *base_address, const int offset, unsigned int dumpsize)
{
    // Step 5: Print dumpsize bytes starting at (base_address + offset).
    // Each row shows: address | 16 hex bytes | ASCII chars (non-printable = '.').
    // Printable ASCII range is 0x20 to 0x7E.

    if (dumpsize < MIN_DUMP_SIZE || dumpsize > MEM_SIZE)
        dumpsize = MIN_DUMP_SIZE;  // enforce minimum dump size of 256 bytes

    unsigned int row, col;
    unsigned int num_rows = dumpsize / DUMP_LINE;  // 16 bytes per row

    for (row = 0; row < num_rows; row++)
    {
        // Pointer to the start of this row in memory
        const unsigned char *row_addr = (const unsigned char *)(base_address + offset + row * DUMP_LINE);

        // Print the row's starting address
        printf("%p: ", (void *)row_addr);

        // Print each byte as 2-digit hex
        for (col = 0; col < DUMP_LINE; col++)
        {
            printf("%02X ", row_addr[col]);
        }

        // Separator between hex and ASCII sections
        printf("--- ");

        // Print ASCII representation; non-printable bytes shown as '.'
        for (col = 0; col < DUMP_LINE; col++)
        {
            unsigned char c = row_addr[col];
            if (c >= 0x20 && c <= 0x7E)
                printf("%c", c);
            else
                printf(".");
        }

        printf("\n");
    }

    return;
}

//---------------------------------------------------------------
void setup_memory()
{
    char *mem = init_memory();  // initialize the 1M memory space.
    char options = 0;
    unsigned int offset, dumpsize;
    char tempchar;
    unsigned int dword_data;

    do {
        if (options != 0x0a)  // skip re-printing menu on bare Enter key
        {
            puts(menu);
            printf("\nThe base address of your memory is: %llXh (HEX)\n",
                   (long long unsigned int)(mem));
            puts("Please make a selection:");
        }
        options = getchar();

        switch (options)
        {
            case '1':  // write double word
                puts("Please input your memory's offset address (in HEX):");
                scanf("%x", (unsigned int *)&offset);
                puts("Please input your DOUBLE WORD data to be written (in HEX):");
                scanf("%x", (unsigned int *)&dword_data);
                write_dword(mem, offset, dword_data);
                continue;

            case '2':  // read byte
                puts("Please input your memory's offset address (in HEX):");
                scanf("%x", &offset);
                read_byte(mem, offset);
                continue;

            case '3':  // read double word
                puts("Please input your memory's offset address (in HEX):");
                scanf("%x", &offset);
                read_dword(mem, offset);
                continue;

            case '4':  // generate memory dump
                puts("Please input your memory's offset address (in HEX, should be a multiple of 0x10h):");
                scanf("%x", &offset);
                puts("Please input the size of the memory to be dumped (between 256 and 1M ):");
                scanf("%d", &dumpsize);
                memory_dump(mem, offset, dumpsize);
                continue;

            case 'e':
            case 'E':
                puts("Code finished, press any key to exit");
                free_memory(mem);
                while ((tempchar = getchar()) != '\n' && tempchar != EOF);
                tempchar = getchar();
                return;

            default:
                continue;
        }
    } while (1);

    return;
}
